# MIT License

# Copyright (c) 2021 Neil Enns, Stefan Herold

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# This workflow generates documentation (PDFs, interactive BOMs, board images). The
# The version number and date of the design is automatically updated in the schematic
# file and on the PCB. The version number is set via an environment variable
# and by default is `pre-release` since this runs outside of the release process
# so there's no formal release number to use.

# To use this workflow in your own repo you need to edit the environment variables in the env: section
# below.


name: "Preflight"

on:
  push:
  pull_request:
    paths:
      - ".*.sch"
      - ".*.kicad_pcb"
      - ".kibot/*.kibot.yaml"
      - ".github/workflows/*.yml"

env:
  OutputFolder: KiBotOutput
  Project: ${{ github.event.repository.name }}

jobs:
  Kibot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Get the commit hash.
      - name: Get GitHub commit hash
        id: vars
        run: echo "::set-output name=commit::$(git rev-parse --short HEAD)"

      # Run KiBot with the preflight script
 #     - uses: INTI-CMNB/KiBot@master
 #       with:
 #         config: .kibot/preflight.kibot.yaml
 #         dir: ${{ env.OutputFolder }}
 #         schema: ${{ env.Project }}.sch
 #         board: ${{ env.Project }}.kicad_pcb
 #         verbose: 2
          
      # Actually run KiBot to generate all the files.
      - name: Generate documentation files
        uses: INTI-CMNB/KiBot@master
        if: ${{ success() }}
        with:
          config: .kibot/documentation2.kibot.yaml
          dir: ${{ env.OutputFolder }}
          schema: ${{ env.Project }}.sch
          board: ${{ env.Project }}.kicad_pcb

      # Archive all the artifacts from output and attach to the action's results.
      - name: Archive logfile artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.Project }}-${{ steps.vars.outputs.commit }}-preflight
          path: ${{ env.OutputFolder }}/**
