# MIT License

# Copyright (c) 2021 Neil Enns, Stefan Herold

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# This workflow generates documentation (PDFs, interactive BOMs, board images). The
# The version number and date of the design is automatically updated in the schematic
# file and on the PCB. The version number is set via an environment variable
# and by default is `pre-release` since this runs outside of the release process
# so there's no formal release number to use.

# To use this workflow in your own repo you need to edit the environment variables in the env: section
# below.


name: "Release"

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Design version"
        required: true
        default: "pre-release"

env:
  # Set this to your local timezone. See https://www.wikiwand.com/en/List_of_tz_database_time_zones for valid strings.
  Timezone: UTC
  # Set this to the output folder for all of the generated files. Unless you have a very
  # good reason to change this you should leave it as KiBotOutput.
  OutputFolder: KiBotOutput
  Project: ${{ github.event.repository.name }}

jobs:
  Kibot:
    runs-on: ubuntu-latest

    # These are all the steps that generate the files.
    steps:
      # Check out the files
      - uses: actions/checkout@v2

      # Get the version of the GitHub release for use later.
      - name: Get GitHub release version
        id: get_github_version
        uses: battila7/get-version-action@v2
        if: startsWith(github.ref, 'refs/tags/')
      - name: Store GitHub release version
        id: save_github_version
        run: echo "version=${{ steps.get_github_version.outputs.version }}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')

      # Get the version from the workflow input. This is only valid
      # when run manually as a workflow.
      - name: Store workflow version
        id: save_workflow_version
        run: echo "version=${{ github.event.inputs.version }}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/') == false

      # Get the current date and time, in the timezone specified above, for use later.
      - name: Get current date and time
        id: get_date
        run: echo "::set-output name=date::$(TZ='${{ env.Timezone }}' date +'%Y-%m-%d %T')"

      # do string replacement in schematic files
      - name: Set schematic version
        uses: jacobtomlinson/gha-find-replace@v1
        with:
          include: ".*.sch"
          find: "%%version%%"
          replace: ${{ env.version }}
      - name: Set schematic date
        uses: jacobtomlinson/gha-find-replace@v1
        with:
          include: ".*.sch"
          find: "%%date%%"
          replace: ${{ steps.get_date.outputs.date }}

      # do string replacement in design files
      - name: Set PCB version
        uses: jacobtomlinson/gha-find-replace@v1
        with:
          include: ".*.kicad_pcb"
          find: "%%version%%"
          replace: ${{ env.version }}
      - name: Set PCB date in page settings
        uses: jacobtomlinson/gha-find-replace@v1
        with:
          include: ".*.kicad_pcb"
          find: "date %%date%%"
          replace: 'date "${{ steps.get_date.outputs.date }}"'
      - name: Set PCB date on PCB layers
        uses: jacobtomlinson/gha-find-replace@v1
        with:
          include: ".*.kicad_pcb"
          find: "%%date%%"
          replace: ${{ steps.get_date.outputs.date }}

      # Actually run KiBot to generate all the files.
      - name: Generate documentation files
        uses: INTI-CMNB/KiBot@master
        with:
          config: .kibot/documentation.kibot.yaml
          dir: ${{ env.OutputFolder }}
          schema: ${{ env.Project }}.sch
          board: ${{ env.Project }}.kicad_pcb
      - name: Generate fabrication files
        uses: INTI-CMNB/KiBot@master
        with:
          config: .kibot/fabrications.kibot.yaml
          dir: ${{ env.OutputFolder }}
          schema: ${{ env.Project }}.sch
          board: ${{ env.Project }}.kicad_pcb

      # Archive all the artifacts from output and attach to the action's results.
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.OutputFolder }}
          path: ${{ env.OutputFolder }}/**


  Publish:
    runs-on: ubuntu-latest
    needs: Kibot

    steps:
      # Get artifacts of privious jobs
      - uses: actions/download-artifact@v2
        with:
          name: ${{ env.OutputFolder }}
    
      # Install the zip command line tool to package up the output
      - name: Install zip
        uses: montudor/action-zip@v1

      # Zip all the documentation.
      - name: Zip JLCPCB fabrication files
        run: zip -qq -j -m "${{ env.Project }}-JLCPCB.zip" gerbers/jlcpcb/*.*
      - name: Zip Oshpark fabrication files
        run: zip -qq -j "${{ env.Project }}-Oshpark.zip" gerbers/*.* docs/bom/*.csv
      - name: Zip PCBWay fabrication files
        run: zip -qq -j "${{ env.Project }}-PCBWay.zip" gerbers/*.* docs/bom/*.csv
      - name: Zip documentation and fabrications
        run: zip -qq -r "${{ env.Project }}.zip" docs cad img *.zip

      # Upload all the zip files to the release.
      - name: Upload release files
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ env.Project }}.zip
            ${{ env.Project }}-JLCPCB.zip
            ${{ env.Project }}-Oshpark.zip
            ${{ env.Project }}-PCBWay.zip

      # Archive all the artifacts from output and attach to the action's results.
      # This is so they're made available when this workflow is run manually from the
      # GitHub actions page.
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gerbers
          path: ${{ github.workspace }}/*.zip

#  OSHWA:
#    runs-on: ubuntu-latest
#    needs: Kibot
#
#    steps:
